server:
  port: 10010
  address: 0.0.0.0
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    item-service: /item/** # 将商品微服务映射到/item/**
    search-service: /search/** # 将商品微服务映射到/search/**
    user-service: /user/** # 将商品微服务映射到/user/**
    auth-service: /auth/** # 将授权微服务映射到/auth/**
    cart-service: /cart/** # 将购物车微服务映射到/cart/**
    order-service: /order/** # 将订单微服务映射到/cart/**
  ignored-services:
    - upload-service # 忽略upload-service服务
  add-host-header: true #携带真实的host header信息
  sensitive-headers: #配置禁止使用的头信息
ribbon:
  ConnectTimeout: 25000 # 连接超时时间(ms)
  ReadTimeout: 20000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 100000 # 熔断超时时长：10000ms
ego:
  jwt:
    pubKeyPath:  E:\workspace\tmp\rsa\rsa.pub # 公钥地址
    cookieName: EGO_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth/
      - /api/search/
      - /api/user/register/
      - /api/user/check/
      - /api/user/code/
      - /api/item/