server:
  port: 8091
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yaorange/springcloudconfig
          search-paths: /**
      label: master
      username: yaorange2019@sina.com
      password: yaorange2019
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
